## Kulturnav - personer

In [ ]:
import urllib3, json
import pandas as pd 
http = urllib3.PoolManager() 
pd.set_option("display.max.columns", None) 
urlbase = "https://kulturnav.org/api/search/entityType:Person?start=" 

dftot = pd.DataFrame()
for i in range(1,300000,20):
    url = urlbase + str(i)
    if ((i-1) % 1000) == 0:
       print('*', end='', flush=True)
    r = http.request('GET', url)
    try:
        data = json.loads(r.data)
        dftot = dftot.append(pd.DataFrame(data),sort=False)
    except:
        print("\tError in i=",i)

*********************************************************************************************************

In [6]:
dftot.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 0 to 19
Data columns (total 13 columns):
uuid                   100000 non-null object
entityType             100000 non-null object
acl                    100000 non-null object
currentVersion         100000 non-null bool
createdAt              100000 non-null object
createdBy              100000 non-null object
inline                 100000 non-null bool
caption                100000 non-null object
properties             100000 non-null object
entityTypeName         100000 non-null object
entityTypeHierarchy    100000 non-null object
updatedAt              95000 non-null object
updatedBy              95000 non-null object
dtypes: bool(2), object(11)
memory usage: 9.3+ MB

In [4]:
dftot

,uuid,entityType,acl,currentVersion,createdAt,createdBy,inline,caption,properties,entityTypeName,entityTypeHierarchy,updatedAt,updatedBy
0,c606934d-b85a-4824-9637-cf0e8fc1c495,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jan 19, 2016 2:41:09 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,False,{},{'entity.dataset': [{'uuid': 'deecb7d7-8a3f-46...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]",NaN,NaN
1,653a04dd-ee17-42a2-badb-2901ceb20420,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 4:18:36 PM",root,False,{'sv': ''},{'entity.dataset': [{'uuid': '59978ea2-2dc8-47...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]","Jan 19, 2016 2:41:15 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e
2,f9683a39-7641-4155-85e6-f051e09e8f67,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 4:09:03 PM",root,False,{'sv': ''},{'entity.alternativeName': [{'uuid': '21f6ccb1...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]","Jan 19, 2016 2:40:34 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e
3,900f2922-7e78-42a7-9b89-8f57505bee6a,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 4:19:38 PM",root,False,"{'sv': '""Irma"" (Irmengard) von Hallwyl'}",{'entity.alternativeName': [{'uuid': '4c27911c...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]","Jan 19, 2016 2:40:36 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e
4,c452c4fe-d94c-410b-9caa-ff541335e749,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 4:04:38 PM",root,False,"{'sv': '""Johnny"" (John August Emanuel) Roosval'}",{'entity.dataset': [{'uuid': '65d1ad7f-cf09-4c...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]","Mar 22, 2016 8:32:29 PM",root
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,08d42da0-25d1-45f1-ad2e-923133b07a93,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 3:06:15 PM",root,False,{'sv': '(Charles) Édouard Boutibonne (1816 - 1...,{'entity.dataset': [{'uuid': '14a89cc3-c43e-4c...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]","Jan 19, 2016 2:07:43 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e
16,c690b94d-5666-4756-9a15-bf5c9fa06f80,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 4:13:57 PM",root,False,{'sv': '(Christian Albin) Waldemar Bülow (1864...,{'entity.alternativeName': [{'uuid': '469cee78...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]","Jan 19, 2016 2:31:27 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e
17,c9d1d01e-815a-4bf2-9c0c-952319fc3f76,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 4:13:15 PM",root,False,{'sv': '(Christina) Matilda Staël von Holstein'},{'entity.alternativeName': [{'uuid': '9dc14680...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]","Jan 19, 2016 2:40:38 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e
18,f7a91513-6314-46aa-84da-1f454127eb52,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 3:25:19 PM",root,False,{'sv': '(Claes Walther) Harry von Eckermann (1...,{'entity.dataset': [{'uuid': '1232b981-6421-40...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]","Jan 19, 2016 2:38:05 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e
19,fae9a387-9c2b-4a8d-b4e3-1a71d466b5d8,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 3:01:05 PM",root,False,{'sv': '(Conrad) Victor Ankarcrona (1823 - 191...,{'entity.dataset': [{'uuid': '59b09bdc-8857-4f...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]","Jan 19, 2016 2:04:35 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e