## Kulturnav - Entity

In [ ]:
import urllib3, json
import pandas as pd 
http = urllib3.PoolManager() 
pd.set_option("display.max.columns", None) 
urlbase = "https://kulturnav.org/api/search/entityType:Entity?start=" 

dftot = pd.DataFrame()
for i in range(1,500000,20):
    url = urlbase + str(i)
    if ((i-1) % 10000) == 0:
       print('*', end='', flush=True)
    r = http.request('GET', url)
    try:
        data = json.loads(r.data)
        dftot = dftot.append(pd.DataFrame(data),sort=False)
    except:
        print("\tError in i=",i)

************************

In [3]:
dftot.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 0 to 19
Data columns (total 14 columns):
uuid                   100000 non-null object
entityType             100000 non-null object
acl                    100000 non-null object
currentVersion         100000 non-null bool
createdAt              100000 non-null object
createdBy              100000 non-null object
updatedAt              60000 non-null object
updatedBy              60000 non-null object
savedSource            85000 non-null object
inline                 100000 non-null bool
caption                100000 non-null object
properties             100000 non-null object
entityTypeName         100000 non-null object
entityTypeHierarchy    100000 non-null object
dtypes: bool(2), object(12)
memory usage: 10.1+ MB

In [4]:
dftot

,uuid,entityType,acl,currentVersion,createdAt,createdBy,updatedAt,updatedBy,savedSource,inline,caption,properties,entityTypeName,entityTypeHierarchy
0,ca7e59b7-639d-427f-985e-32ac004cdf1c,Organization,330ccd5c-9137-45a3-8f91-fa043c0e177b_SHARED,True,"Oct 27, 2016 2:33:48 PM",88cdbbbc-3cd6-4dd6-8d3e-c865f89d8d85,"Oct 28, 2016 1:40:36 PM",88cdbbbc-3cd6-4dd6-8d3e-c865f89d8d85,SCRIPT: extractDrafts,False,{},{'dataset.primaryLanguage': [{'uuid': '734bae0...,"{'nn': 'Organisasjon', 'no': 'Organisasjon', '...","[Agent, Organization]"
1,c606934d-b85a-4824-9637-cf0e8fc1c495,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jan 19, 2016 2:41:09 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,NaN,NaN,NaN,False,{},{'entity.dataset': [{'uuid': 'deecb7d7-8a3f-46...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]"
2,5b599743-acfb-4296-a252-347a525f8977,List,5b599743-acfb-4296-a252-347a525f8977_SHARED,True,"Dec 6, 2018 10:24:27 AM",f7c95265-132a-464d-9012-fdbea7c99155,NaN,NaN,INTERACTIVE,False,{'en': ''},{'dataset.privateAcl': [{'uuid': '855a7e66-e66...,"{'nn': 'Mappe', 'no': 'Mappe', 'sv': 'Mapp', '...","[Dataset, List]"
3,653a04dd-ee17-42a2-badb-2901ceb20420,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 4:18:36 PM",root,"Jan 19, 2016 2:41:15 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,NaN,False,{'sv': ''},{'entity.dataset': [{'uuid': '59978ea2-2dc8-47...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]"
4,f9683a39-7641-4155-85e6-f051e09e8f67,Person,4c1319c2-a30a-43e7-a3d5-05038935dcfb_SHARED,True,"Jun 11, 2013 4:09:03 PM",root,"Jan 19, 2016 2:40:34 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,NaN,False,{'sv': ''},{'entity.alternativeName': [{'uuid': '21f6ccb1...,"{'nn': 'Person', 'no': 'Person', 'sv': 'Person...","[Agent, Person]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,288b1fc9-6f8a-4a60-ad9e-ab10055a0e5c,List,288b1fc9-6f8a-4a60-ad9e-ab10055a0e5c_SHARED,True,"Apr 14, 2016 3:16:16 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,"Apr 19, 2016 6:55:47 AM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,SCRIPT: migrateList,True,{'sv': '__DIMU_HARVEST (KulturIT AS)'},{'dataset.contentUpdatedAt': [{'uuid': '275929...,"{'nn': 'Mappe', 'no': 'Mappe', 'sv': 'Mapp', '...","[Dataset, List]"
16,6de31df5-5566-4814-b661-59b3c88fb226,List,6de31df5-5566-4814-b661-59b3c88fb226_SHARED,True,"Mar 31, 2017 8:58:41 AM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,NaN,NaN,SCRIPT: migrateList,False,{'sv': '__DIMU_HARVEST_prep'},{'dataset.contentUpdatedAt': [{'uuid': '13e776...,"{'nn': 'Mappe', 'no': 'Mappe', 'sv': 'Mapp', '...","[Dataset, List]"
17,5559aabc-c0b5-4367-a7cc-cb7e8635d9c2,List,5559aabc-c0b5-4367-a7cc-cb7e8635d9c2_SHARED,True,"Oct 13, 2016 4:35:46 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,"Mar 20, 2017 7:58:13 AM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,SCRIPT: migrateList,True,{'sv': '__DIMU_PERIODS (KulturIT AS)'},{'dataset.contentUpdatedAt': [{'uuid': 'c14e8c...,"{'nn': 'Mappe', 'no': 'Mappe', 'sv': 'Mapp', '...","[Dataset, List]"
18,d65cf2f9-4ff9-40b7-a871-dad9fe84cb20,List,d65cf2f9-4ff9-40b7-a871-dad9fe84cb20_SHARED,True,"Mar 20, 2017 7:54:48 AM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,"Mar 20, 2017 7:57:38 AM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,SCRIPT: migrateList,False,{'sv': '__DIMU_PLACES (KulturIT AS)'},{'dataset.contentUpdatedAt': [{'uuid': '78b129...,"{'nn': 'Mappe', 'no': 'Mappe', 'sv': 'Mapp', '...","[Dataset, List]"
19,1b9e08ed-0087-4326-8e9c-4cd5e7913c84,List,1b9e08ed-0087-4326-8e9c-4cd5e7913c84_SHARED,True,"Oct 16, 2019 7:00:09 PM",root,"Mar 26, 2020 3:41:45 PM",7b89c094-da28-4fdb-bcd2-ce0db0df923e,INTERACTIVE,False,{'sv': '__DIMU_STAGING (KulturIT AS)'},{'dataset.owner': [{'uuid': '4fddf788-d2bf-42c...,"{'nn': 'Mappe', 'no': 'Mappe', 'sv': 'Mapp', '...","[Dataset, List]"

In [5]:
dftot.entityType.value_counts()

List            80000
Person          15000
Organization     5000
Name: entityType, dtype: int64