**Work in progress**


# Nobel API 2.1 - check Wikidata and Nobel API

The purpose of this Notebook is to have Nobelprize winners in Wikidata in synch with the prizewinners at Nobelprize... lesson learned is that we also find vandalization in Wikidata....


* This [Jupyter Notebook](https://github.com/salgo60/open-data-examples/blob/master/Nobel%20API_2_1.ipynb)  using API 2.1 [api.nobelprize.org/2.1/laureates](https://api.nobelprize.org/2.1/laureates)
  * old [Notebook](https://github.com/salgo60/open-data-examples/blob/master/Nobel%20API.ipynb)


  * Wikidata property [Property:P8024](https://www.wikidata.org/wiki/Property:P8024)
  * [Developer zone nobelprize.org](https://www.nobelprize.org/about/developer-zone-2/)
      * API 2.1 [api.nobelprize.org/2.1/laureates](https://api.nobelprize.org/2.1/laureates)
  * [video](https://youtu.be/Iu1JtefueM8) explaining what we do
  
#### Misc
Version history
* 0.1 use API 2.1 --> Nobel API also includes Wikidata Q numbers
##### See also
* Kaggle [nobelfoundation/nobel-laureates](https://www.kaggle.com/nobelfoundation/nobel-laureates) and my [Kaggle Notebook](https://www.kaggle.com/magnusslg/wikidata-nobelprize-synch)

#### Other sources we sync
* Famous people on Uppsala old cemetery [Kulturpersoner Uppsalakyrkog√•rd](https://github.com/salgo60/open-data-examples/blob/master/Check%20WD%20kulturpersoner%20uppsalakyrkogardar.ipynb)
* Swedish Literature Bank - [Litteraturbanken](https://github.com/salgo60/open-data-examples/blob/master/Litteraturbanken%20Author.ipynb) 
  * WD property [P5101](https://www.wikidata.org/wiki/Property_talk:P5101) [P5123](https://www.wikidata.org/wiki/Property_talk:P5123)
* [Nobelprize.org](https://github.com/salgo60/open-data-examples/blob/master/Nobel%20API.ipynb)
  * WD [property 8024](https://www.wikidata.org/wiki/Property:P8024)
* The Swedish National Archive [SBL](https://github.com/salgo60/open-data-examples/blob/master/SBL.ipynb) 
  * WD [property 3217](https://www.wikidata.org/wiki/Property:P3217) 
* The Biographical Dictionary of Swedish Women [SKBL](https://github.com/salgo60/open-data-examples/blob/master/Svenskt%20Kvinnobiografiskt%20lexikon%20part%203.ipynb)
  * WD [property 4963](https://www.wikidata.org/wiki/Property:P4963)
* Swedish Academy - [Svenska Akademien](https://github.com/salgo60/open-data-examples/blob/master/Svenska%20Akademien.ipynb) 
  * WD [property 5325](https://www.wikidata.org/wiki/Property:P5325)

In [1]:
from datetime import datetime
start_time = datetime.now()
print("Last run: ", datetime.now())

Last run:  2021-10-05 08:16:26.487727

In [2]:
import urllib3, json
import pandas as pd 
http = urllib3.PoolManager() 

url ="https://api.nobelprize.org/2.1/laureates?offset=0&limit=1500"
dftot = pd.DataFrame()
r = http.request('GET', url)
data = json.loads(r.data)
dftot = dftot.append(pd.DataFrame(data["laureates"]),sort=False)

In [3]:
dftot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 957 entries, 0 to 956
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 957 non-null    object
 1   knownName          932 non-null    object
 2   givenName          932 non-null    object
 3   familyName         930 non-null    object
 4   fullName           932 non-null    object
 5   fileName           957 non-null    object
 6   gender             932 non-null    object
 7   birth              931 non-null    object
 8   wikipedia          957 non-null    object
 9   wikidata           957 non-null    object
 10  sameAs             957 non-null    object
 11  links              957 non-null    object
 12  nobelPrizes        957 non-null    object
 13  death              641 non-null    object
 14  orgName            25 non-null     object
 15  nativeName         24 non-null     object
 16  acronym            11 non-null     object
 17  founded            24 non-null     object
 18  penName            11 non-null     object
 19  birthCountry       1 non-null      object
 20  birthCountryNow    1 non-null      object
 21  birthContinent     1 non-null      object
 22  foundedCountry     1 non-null      object
 23  foundedCountryNow  1 non-null      object
 24  foundedContinent   1 non-null      object
dtypes: object(25)
memory usage: 187.0+ KB

In [4]:
dftot["id"] = dftot["id"].astype("int")

dftot.sort_values(by=['id'], ascending=[True], inplace=True)
dftot.tail(4)

,id,knownName,givenName,familyName,fullName,fileName,gender,birth,wikipedia,wikidata,...,nativeName,acronym,founded,penName,birthCountry,birthCountryNow,birthContinent,foundedCountry,foundedCountryNow,foundedContinent
682,995,"{'en': 'Paul R. Milgrom', 'se': 'Paul R. Milgr...","{'en': 'Paul', 'se': 'Paul'}","{'en': 'Milgrom', 'se': 'Milgrom'}","{'en': 'Paul R. Milgrom', 'se': 'Paul R. Milgr...",milgrom,male,"{'date': '1948-04-20', 'place': {'city': {'en'...","{'slug': 'Paul_Milgrom', 'english': 'https://e...","{'id': 'Q1359990', 'url': 'https://www.wikidat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
743,996,"{'en': 'Robert B. Wilson', 'se': 'Robert B. Wi...","{'en': 'Robert', 'se': 'Robert'}","{'en': 'Wilson', 'se': 'Wilson'}","{'en': 'Robert B. Wilson', 'se': 'Robert B. Wi...",wilson,male,"{'date': '1937-05-16', 'place': {'city': {'en'...","{'slug': 'Robert_B._Wilson', 'english': 'https...","{'id': 'Q377265', 'url': 'https://www.wikidata...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,997,"{'en': 'David Julius', 'se': 'David Julius'}","{'en': 'David', 'se': 'David'}","{'en': 'Julius', 'se': 'Julius'}","{'en': 'David Julius', 'se': 'David Julius'}",julius,male,"{'date': '1955-11-04', 'place': {'city': {'en'...","{'slug': 'David_Julius', 'english': 'https://e...","{'id': 'Q1174906', 'url': 'https://www.wikidat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,998,"{'en': 'Ardem Patapoutian', 'se': 'Ardem Patap...","{'en': 'Ardem', 'se': 'Ardem'}","{'en': 'Patapoutian', 'se': 'Patapoutian'}","{'en': 'Ardem Patapoutian', 'se': 'Ardem Patap...",patapoutian,male,"{'date': '1967-00-00', 'place': {'city': {'en'...","{'slug': 'Ardem_Patapoutian', 'english': 'http...","{'id': 'Q60322501', 'url': 'https://www.wikida...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Test flatten 
#from pandas.json_normalize import json_normalize
#from pandas.io.json.normalize import nested_to_record
from pandas import json_normalize
#dftotPrize = json_normalize(data=data['laureates'], record_path='nobelPrizes', 
#                            meta=['id', 'filename','gender', 'wikidata'],errors='ignore') 
dftotPrize = json_normalize(data=data["laureates"])
dftotPrize.shape

(957, 107)

In [6]:
dftotPrize.sample(5)

,id,fileName,gender,sameAs,links,nobelPrizes,knownName.en,knownName.se,givenName.en,givenName.se,...,givenName.no,familyName.no,fullName.no,foundedCountry.en,foundedCountry.no,foundedCountry.se,foundedCountryNow.en,foundedCountryNow.no,foundedCountryNow.se,foundedContinent.en
666,679,samuelson,male,"[https://www.wikidata.org/wiki/Q102454, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1970', 'category': {'en': 'Eco...",Paul A. Samuelson,Paul A. Samuelson,Paul A.,Paul A.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
881,670,morrison,female,"[https://www.wikidata.org/wiki/Q72334, https:/...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1993', 'category': {'en': 'Lit...",Toni Morrison,Toni Morrison,Toni,Toni,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,745,spence,male,"[https://www.wikidata.org/wiki/Q157245, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2001', 'category': {'en': 'Eco...",A. Michael Spence,A. Michael Spence,A. Michael,A. Michael,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,880,yan,male,"[https://www.wikidata.org/wiki/Q8998, https://...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2012', 'category': {'en': 'Lit...",Mo Yan,Mo Yan,Mo,Mo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
764,96,schrieffer,male,"[https://www.wikidata.org/wiki/Q153201, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1972', 'category': {'en': 'Phy...",Robert Schrieffer,Robert Schrieffer,Robert,Robert,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
dftotPrize["penName"].value_counts()

(pen-name of Odysseus Alepoudhelis)             1
(pen-name of Lucila Godoy y Alcayaga)           1
(pen-name of Grazia Madesani, n√©e Deledda)      1
(pen-name of Jacques Anatole Thibault)          1
(pen-name of Pearl Walsh, n√©e Sydenstricker)    1
(pen-name of Rejment)                           1
(pen-name of Giorgos Seferiadis)                1
(pen-name of Guan Moye)                         1
(pen-name of Alexis L√©ger)                      1
(pen-name of Neftal√≠ Ricardo Reyes Basoalto)    1
(pen-name of Ren√© Fran√ßois Armand Prudhomme)    1
Name: penName, dtype: int64

In [8]:
dftotPrize["birth.place.countryNow.en"].value_counts()

USA                    280
United Kingdom          87
Germany                 82
France                  57
Sweden                  29
                      ...
Vietnam                  1
Trinidad and Tobago      1
Zimbabwe                 1
Yemen                    1
Taiwan                   1
Name: birth.place.countryNow.en, Length: 83, dtype: int64

In [9]:
dftotPrize.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 957 entries, 0 to 956
Columns: 107 entries, id to foundedContinent.en
dtypes: object(107)
memory usage: 800.1+ KB

In [10]:
#dftotPrize["death.place.country.sameAs"].value_counts()

In [11]:
dftotPrize.sample(4)

,id,fileName,gender,sameAs,links,nobelPrizes,knownName.en,knownName.se,givenName.en,givenName.se,...,givenName.no,familyName.no,fullName.no,foundedCountry.en,foundedCountry.no,foundedCountry.se,foundedCountryNow.en,foundedCountryNow.no,foundedCountryNow.se,foundedContinent.en
508,586,gjellerup,male,"[https://www.wikidata.org/wiki/Q131487, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1917', 'category': {'en': 'Lit...",Karl Gjellerup,Karl Gjellerup,Karl,Karl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
711,385,granit,male,"[https://www.wikidata.org/wiki/Q217722, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1967', 'category': {'en': 'Phy...",Ragnar Granit,Ragnar Granit,Ragnar,Ragnar,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,60,zernike,male,"[https://www.wikidata.org/wiki/Q188293, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1953', 'category': {'en': 'Phy...",Frits Zernike,Frits Zernike,Frits,Frits,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,758,wuthrich,male,"[https://www.wikidata.org/wiki/Q110957, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2002', 'category': {'en': 'Che...",Kurt W√ºthrich,Kurt W√ºthrich,Kurt,Kurt,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Check Wikidata matches

In [12]:
# pip install sparqlwrapper
# https://rdflib.github.io/sparqlwrapper/

import sys
from SPARQLWrapper import SPARQLWrapper, JSON

endpoint_url = "https://query.wikidata.org/sparql"

query = """SELECT ?WDitem ?WDitemLabel ?WDNobelAPI ?WDdeath WHERE {
  ?WDitem wdt:P8024 ?WDNobelAPI.
  OPTIONAL {?WDitem wdt:P570 ?WDdeath}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
} order by xsd:integer(?WDNobelAPI)"""


def get_sparql_dataframe(endpoint_url, query):
    """
    Helper function to convert SPARQL results into a Pandas data frame.
    """
    user_agent = "salgo60/%s.%s" % (sys.version_info[0], sys.version_info[1])
 
    sparql = SPARQLWrapper(endpoint_url, agent=user_agent)
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    result = sparql.query()

    processed_results = json.load(result.response)
    cols = processed_results['head']['vars']
    out = []
    for row in processed_results['results']['bindings']:
        item = []
        for c in cols:
            item.append(row.get(c, {}).get('value'))
        out.append(item)

    return pd.DataFrame(out, columns=cols)

WDNobel = get_sparql_dataframe(endpoint_url, query)

In [13]:
WDNobel["WDNobelAPI"] = WDNobel["WDNobelAPI"].astype("int")
WDNobel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WDitem       970 non-null    object
 1   WDitemLabel  970 non-null    object
 2   WDNobelAPI   970 non-null    int64
 3   WDdeath      655 non-null    object
dtypes: int64(1), object(3)
memory usage: 30.4+ KB

### Compare WD <-> Nobel

In [14]:
WDNobel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WDitem       970 non-null    object
 1   WDitemLabel  970 non-null    object
 2   WDNobelAPI   970 non-null    int64
 3   WDdeath      655 non-null    object
dtypes: int64(1), object(3)
memory usage: 30.4+ KB

In [15]:
dftotPrize["id"] = dftotPrize["id"].astype("int")

#dftotPrize.info()

In [16]:
dfmerge = pd.merge(WDNobel, dftotPrize,how='outer', left_on="WDNobelAPI",right_on="id",indicator=True)
dfmerge['_merge'] = dfmerge['_merge'].str.replace('left_only','WD_only').str.replace('right_only','Nobel_only')
dfmerge.rename(columns={"_merge": "WD_Nobel"},inplace = True)    
#dfmerge[-10:]

In [17]:
dfmerge[dfmerge["WD_Nobel"]!="both"]

Empty DataFrame
Columns: [WDitem, WDitemLabel, WDNobelAPI, WDdeath, id, fileName, gender, sameAs, links, nobelPrizes, knownName.en, knownName.se, givenName.en, givenName.se, familyName.en, familyName.se, fullName.en, fullName.se, birth.date, birth.place.city.en, birth.place.city.no, birth.place.city.se, birth.place.country.en, birth.place.country.no, birth.place.country.se, birth.place.cityNow.en, birth.place.cityNow.no, birth.place.cityNow.se, birth.place.cityNow.sameAs, birth.place.countryNow.en, birth.place.countryNow.no, birth.place.countryNow.se, birth.place.countryNow.sameAs, birth.place.continent.en, birth.place.continent.no, birth.place.continent.se, birth.place.locationString.en, birth.place.locationString.no, birth.place.locationString.se, wikipedia.slug, wikipedia.english, wikidata.id, wikidata.url, death.date, death.place.city.en, death.place.city.no, death.place.city.se, death.place.country.en, death.place.country.no, death.place.country.se, death.place.country.sameAs, death.place.cityNow.en, death.place.cityNow.no, death.place.cityNow.se, death.place.cityNow.sameAs, death.place.countryNow.en, death.place.countryNow.no, death.place.countryNow.se, death.place.countryNow.sameAs, death.place.continent.en, death.place.continent.no, death.place.continent.se, death.place.locationString.en, death.place.locationString.no, death.place.locationString.se, nativeName, acronym, orgName.en, orgName.no, orgName.se, founded.date, founded.place.city.en, founded.place.city.no, founded.place.city.se, founded.place.country.en, founded.place.country.no, founded.place.country.se, founded.place.country.sameAs, founded.place.cityNow.en, founded.place.cityNow.no, founded.place.cityNow.se, founded.place.cityNow.sameAs, founded.place.countryNow.en, founded.place.countryNow.no, founded.place.countryNow.se, founded.place.countryNow.sameAs, founded.place.continent.en, founded.place.continent.no, founded.place.continent.se, founded.place.locationString.en, founded.place.locationString.no, founded.place.locationString.se, penName, birthCountry.en, birthCountry.no, birthCountry.se, birthCountryNow.en, birthCountryNow.no, birthCountryNow.se, birthContinent.en, ...]
Index: []

[0 rows x 112 columns]

In [18]:
WDNobel['wikidata'] = WDNobel['WDitem'].str.replace('http://www.wikidata.org/entity/','')

<ipython-input-18-148fcb106129>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  WDNobel['wikidata'] = WDNobel['WDitem'].str.replace('http://www.wikidata.org/entity/','')

In [19]:
WDNobel.head()

,WDitem,WDitemLabel,WDNobelAPI,WDdeath,wikidata
0,http://www.wikidata.org/entity/Q35149,Wilhelm R√∂ntgen,1,1923-02-10T00:00:00Z,Q35149
1,http://www.wikidata.org/entity/Q41688,Hendrik Lorentz,2,1928-02-04T00:00:00Z,Q41688
2,http://www.wikidata.org/entity/Q79000,Pieter Zeeman,3,1943-10-09T00:00:00Z,Q79000
3,http://www.wikidata.org/entity/Q41269,Henri Becquerel,4,1908-08-25T00:00:00Z,Q41269
4,http://www.wikidata.org/entity/Q37463,Pierre Curie,5,1906-04-19T00:00:00Z,Q37463

In [20]:
WDNobel.tail()

,WDitem,WDitemLabel,WDNobelAPI,WDdeath,wikidata
965,http://www.wikidata.org/entity/Q204344,World Food Programme,994,None,Q204344
966,http://www.wikidata.org/entity/Q1359990,Paul Milgrom,995,None,Q1359990
967,http://www.wikidata.org/entity/Q377265,Robert B. Wilson,996,None,Q377265
968,http://www.wikidata.org/entity/Q1174906,David Julius,997,None,Q1174906
969,http://www.wikidata.org/entity/Q60322501,Ardem Patapoutian,998,None,Q60322501

In [21]:
#Merge on the Wikidata Qnumber at NobelTot  
dfmergeWD = pd.merge(WDNobel, dftotPrize,how='outer', left_on="wikidata",right_on="wikidata.id",indicator=True)
dfmergeWD['_merge'] = dfmergeWD['_merge'].str.replace('left_only','WD_only').str.replace('right_only','Nobel_only')
dfmergeWD.rename(columns={"_merge": "WD_Nobel"},inplace = True)    
dfmergeWD["WD_Nobel"].value_counts()

both          969
Nobel_only      2
WD_only         1
Name: WD_Nobel, dtype: int64

In [22]:
dfmergeWD[dfmergeWD["WD_Nobel"]!="both"]

,WDitem,WDitemLabel,WDNobelAPI,WDdeath,wikidata,id,fileName,gender,sameAs,links,...,familyName.no,fullName.no,foundedCountry.en,foundedCountry.no,foundedCountry.se,foundedCountryNow.en,foundedCountryNow.no,foundedCountryNow.se,foundedContinent.en,WD_Nobel
819,http://www.wikidata.org/entity/Q42037,Jean-Marie Gustave Le Cl√©zio,832.0,None,Q42037,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WD_only
970,NaN,NaN,NaN,NaN,NaN,832.0,clezio,male,"[https://www.wikidata.org/wiki/Q7884119, https...","[{'rel': 'laureate', 'href': 'https://api.nobe...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nobel_only
971,NaN,NaN,NaN,NaN,NaN,523.0,red-cross-league,NaN,"[https://www.wikidata.org/wiki/Q1069175, https...","[{'rel': 'laureate', 'href': 'https://api.nobe...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nobel_only

#### Check that Wikidata and api.nobelprize.org is in synch

In [23]:
dfmerge["WD_Nobel"].value_counts()

both    970
Name: WD_Nobel, dtype: int64

In [24]:
Nobelonly = dfmerge[dfmerge["WD_Nobel"]=="Nobel_only"].copy() 

from IPython.display import HTML
Nobelonly["Nobel"] = "<a href='https://api.nobelprize.org/v1/laureate.json?id=" + Nobelonly["id"] + "'>link</a>"
Nobelonly["Nobelhtml"] = "<a href='https://www.nobelprize.org/laureate/" + Nobelonly["id"] + "'>html</a>"
pd.set_option("display.max.columns", None) 
HTML(Nobelonly.to_html(escape=False))

In [25]:
dfmerge.to_csv("Nobel_dfmerge_2_1.csv")
Nobelonly.to_csv("Nobel_only.csv")

In [26]:
WDonly = dfmerge[dfmerge["WD_Nobel"]=="WD_only"].copy() 
WDonly

Empty DataFrame
Columns: [WDitem, WDitemLabel, WDNobelAPI, WDdeath, id, fileName, gender, sameAs, links, nobelPrizes, knownName.en, knownName.se, givenName.en, givenName.se, familyName.en, familyName.se, fullName.en, fullName.se, birth.date, birth.place.city.en, birth.place.city.no, birth.place.city.se, birth.place.country.en, birth.place.country.no, birth.place.country.se, birth.place.cityNow.en, birth.place.cityNow.no, birth.place.cityNow.se, birth.place.cityNow.sameAs, birth.place.countryNow.en, birth.place.countryNow.no, birth.place.countryNow.se, birth.place.countryNow.sameAs, birth.place.continent.en, birth.place.continent.no, birth.place.continent.se, birth.place.locationString.en, birth.place.locationString.no, birth.place.locationString.se, wikipedia.slug, wikipedia.english, wikidata.id, wikidata.url, death.date, death.place.city.en, death.place.city.no, death.place.city.se, death.place.country.en, death.place.country.no, death.place.country.se, death.place.country.sameAs, death.place.cityNow.en, death.place.cityNow.no, death.place.cityNow.se, death.place.cityNow.sameAs, death.place.countryNow.en, death.place.countryNow.no, death.place.countryNow.se, death.place.countryNow.sameAs, death.place.continent.en, death.place.continent.no, death.place.continent.se, death.place.locationString.en, death.place.locationString.no, death.place.locationString.se, nativeName, acronym, orgName.en, orgName.no, orgName.se, founded.date, founded.place.city.en, founded.place.city.no, founded.place.city.se, founded.place.country.en, founded.place.country.no, founded.place.country.se, founded.place.country.sameAs, founded.place.cityNow.en, founded.place.cityNow.no, founded.place.cityNow.se, founded.place.cityNow.sameAs, founded.place.countryNow.en, founded.place.countryNow.no, founded.place.countryNow.se, founded.place.countryNow.sameAs, founded.place.continent.en, founded.place.continent.no, founded.place.continent.se, founded.place.locationString.en, founded.place.locationString.no, founded.place.locationString.se, penName, birthCountry.en, birthCountry.no, birthCountry.se, birthCountryNow.en, birthCountryNow.no, birthCountryNow.se, birthContinent.en, ...]
Index: []

In [27]:
print("End run: ", datetime.now())

End run:  2021-10-05 08:16:30.871535

In [28]:
print('Time elapsed (hh:mm:ss.ms) {}'.format(datetime.now() - start_time))

Time elapsed (hh:mm:ss.ms) 0:00:04.388922

In [29]:
for l, r in dfmerge.iterrows():
    #print (l,r["nobelPrizes"][0]["awardYear"],r["nobelPrizes"][0]["category"]["en"])
    dfmerge.at[l,"awardYear"] = r["nobelPrizes"][0]["awardYear"]
    dfmerge.at[l,"category"]= r["nobelPrizes"][0]["category"]["en"]

## Lesson learned
Its a delay when the html page is linked after the announcement --> we do this list below to check when its ready and we can add it to Wikidata and the WIkipedia article

In [30]:
pd.set_option("max_info_columns", 140)
#dfmerge.info()

In [31]:
# see task xxx we can create links JSOn and HTML using the ID
dfmerge["linkjson"] = "<a href='https://api.nobelprize.org/v1/laureate.json?id=" + dfmerge["id"].astype(str) + "'>json</a>"
dfmerge["linkhtml"] = "<a href='https://www.nobelprize.org/laureate/" + dfmerge["id"].astype(str) + "'>html</a>"
dfmerge["wd"] = "<a href='" + dfmerge["WDitem"].astype(str) + "'>Wikidata</a>"

pd.set_option("display.max.columns", None) 
HTML(dfmerge[{'wd','knownName.en','awardYear','category','linkjson','linkhtml'}].tail(15).to_html(escape=False))

Status 20201009 :
* Ok all has html pages

Templates supporting Wikidata Property 8024 = Wikidata [Q91652187](https://www.wikidata.org/wiki/Q91652187)
* ar:Wikipedia [ŸÇÿßŸÑÿ®:ÿ¨ÿßÿ¶ÿ≤ÿ©_ŸÜŸàÿ®ŸÑ](https://ar.wikipedia.org/wiki/%D9%82%D8%A7%D9%84%D8%A8:%D8%AC%D8%A7%D8%A6%D8%B2%D8%A9_%D9%86%D9%88%D8%A8%D9%84)
* ca:wikipedia [Plantilla:Nobelprize](https://ca.wikipedia.org/wiki/Plantilla:Nobelprize)
* en:Wikipedia [Template:Nobelprize](https://en.wikipedia.org/wiki/Template:Nobelprize)
* ka:Wikipedia [·Éó·Éê·É†·Éí·Éò:Nobelprize](https://ka.wikipedia.org/wiki/%E1%83%97%E1%83%90%E1%83%A0%E1%83%92%E1%83%98:Nobelprize)
* nn:Wikipedia [Mal:Nobelprize](https://nn.wikipedia.org/wiki/Mal:Nobelprize)
* pt:Wikipedia [Predefini√ß√£o:Pr√©mio Nobel](https://pt.wikipedia.org/wiki/Predefini%C3%A7%C3%A3o:Pr%C3%A9mio_Nobel)
* sv:Wikipedia [Mall:Nobelprize](https://sv.wikipedia.org/wiki/Mall:Nobelprize)
* sr:WIkipedia [–®–∞–±–ª–æ–Ω:Nobelprize](https://sr.wikipedia.org/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:Nobelprize)

* Articles using [template](https://www.wikidata.org/wiki/Q91652187) and view statistics this year and during the [Nobel week](https://www.nobelprize.org/press/#/publication/5f1719e411aab40004a17f36/552bd85dccc8e20c00e7f979?&sh=false)  5-12 October 2020 on those articles see also [video](https://youtu.be/Iu1JtefueM8)
  * ar:Wikipedia [using](https://petscan.wmflabs.org/?psid=17573153) / not using
    * [statistics](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&range=this-year&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://ar.wikipedia.org/wiki/%25D8%25AA%25D8%25B5%25D9%2586%25D9%258A%25D9%2581:%25D9%2582%25D8%25A7%25D9%2584%25D8%25A8_%25D8%25AC%25D8%25A7%25D8%25A6%25D8%25B2%25D8%25A9_%25D9%2586%25D9%2588%25D8%25A8%25D9%2584_%25D9%258A%25D8%25B3%25D8%25AA%25D8%25B9%25D9%2585%25D9%2584_%25D8%25AE%25D8%25A7%25D8%25B5%25D8%25A9_%25D9%2588%25D9%258A%25D9%2583%25D9%258A_%25D8%25A8%25D9%258A%25D8%25A7%25D9%2586%25D8%25A7%25D8%25AA_P8024) / [Nobel week](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-12&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://ar.wikipedia.org/wiki/%25D8%25AA%25D8%25B5%25D9%2586%25D9%258A%25D9%2581:%25D9%2582%25D8%25A7%25D9%2584%25D8%25A8_%25D8%25AC%25D8%25A7%25D8%25A6%25D8%25B2%25D8%25A9_%25D9%2586%25D9%2588%25D8%25A8%25D9%2584_%25D9%258A%25D8%25B3%25D8%25AA%25D8%25B9%25D9%2585%25D9%2584_%25D8%25AE%25D8%25A7%25D8%25B5%25D8%25A9_%25D9%2588%25D9%258A%25D9%2583%25D9%258A_%25D8%25A8%25D9%258A%25D8%25A7%25D9%2586%25D8%25A7%25D8%25AA_P8024)
  * ca:Wikipedia miss track category [Q91672712](https://www.wikidata.org/wiki/Q91672712#sitelinks-wikipedia)
  * en:Wikipedia [using](https://petscan.wmflabs.org/?psid=17573140) / [not using](https://petscan.wmflabs.org/?psid=17579263) 
    * [statistics](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&range=this-year&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://en.wikipedia.org/wiki/Category:Nobelprize_template_using_Wikidata_property_P8024) / [Nobel week](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-12&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://en.wikipedia.org/wiki/Category:Nobelprize_template_using_Wikidata_property_P8024) as a [chart](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-10&subjectpage=0&subcategories=0&sort=views&direction=1&view=chart&target=https://en.wikipedia.org/wiki/Category:Nobelprize%20template%20using%20Wikidata%20property%20P8024)
  * ka:Wikipedia miss track category [Q91672712](https://www.wikidata.org/wiki/Q91672712#sitelinks-wikipedia)
  * nn:Wikipedia [using](https://petscan.wmflabs.org/?psid=17573155) / not using 
     * [statistics](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&range=this-year&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://nn.wikipedia.org/wiki/Kategori:Sider_som_nyttar_Mal:Nobelprize) / [Nobel week](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-12&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://nn.wikipedia.org/wiki/Kategori:Sider_som_nyttar_Mal:Nobelprize)
  * pt:Wikipedia [using](https://petscan.wmflabs.org/?psid=17573158) / [not using](https://petscan.wmflabs.org/?psid=17579612) 
     * [statistics](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&range=this-year&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://pt.wikipedia.org/wiki/Categoria:Predefini%25C3%25A7%25C3%25A3o_sobre_pr%25C3%25A9mios_Nobel_que_usam_a_propriedade_do_Wikidata_P8024) / [Nobel week](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-12&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://pt.wikipedia.org/wiki/Categoria:Predefini%25C3%25A7%25C3%25A3o_sobre_pr%25C3%25A9mios_Nobel_que_usam_a_propriedade_do_Wikidata_P8024)
  * sv:Wikipedia [using](https://petscan.wmflabs.org/?psid=17573129) / not using 
    * [statistics](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&range=this-year&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://sv.wikipedia.org/wiki/Kategori:Sidor_som_anv%25C3%25A4nder_Mall:Nobelprize) / [Nobel week](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-12&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://sv.wikipedia.org/wiki/Kategori:Sidor_som_anv%25C3%25A4nder_Mall:Nobelprize)
  * sr:Wikipedia miss track category [Q91672712](https://www.wikidata.org/wiki/Q91672712#sitelinks-wikipedia)
  
Task [T251055](https://phabricator.wikimedia.org/T251055)

# Next Nobelprize announcement
see https://www.nobelprize.org/