# Nobel API 2.1 - check Wikidata and Nobel API

The purpose of this Notebook is to have Nobelprize winners in Wikidata in synch with the prizewinners at Nobelprize... lesson learned is that we also find vandalization in Wikidata....


* This [Jupyter Notebook](https://tinyurl.com/SynchWSNobel)  


  * Wikidata property [Property:P8024](https://www.wikidata.org/wiki/Property:P8024)
  * [Developer zone nobelprize.org](https://www.nobelprize.org/about/developer-zone-2/)
      * API 2.0 [api.nobelprize.org/2.0/laureates](https://api.nobelprize.org/2.0/laureates)
      * API 2.1 [api.nobelprize.org/2.1/laureates](https://api.nobelprize.org/2.1/laureates)
  * [video](https://youtu.be/Iu1JtefueM8) explaining what we do
  
#### Misc
Version history
* 0.1 changed to use API 2.1 --> Nobel API also includes Wikidata Q numbers
##### See also
* Kaggle [nobelfoundation/nobel-laureates](https://www.kaggle.com/nobelfoundation/nobel-laureates) and my [Kaggle Notebook](https://www.kaggle.com/magnusslg/wikidata-nobelprize-synch)
      
#### Other sources we sync
* Famous people on Uppsala old cemetery [Kulturpersoner Uppsalakyrkogård](https://github.com/salgo60/open-data-examples/blob/master/Check%20WD%20kulturpersoner%20uppsalakyrkogardar.ipynb)
* Swedish Literature Bank - [Litteraturbanken](https://github.com/salgo60/open-data-examples/blob/master/Litteraturbanken%20Author.ipynb) 
  * WD property [P5101](https://www.wikidata.org/wiki/Property_talk:P5101) [P5123](https://www.wikidata.org/wiki/Property_talk:P5123)
* [Nobelprize.org](https://github.com/salgo60/open-data-examples/blob/master/Nobel%20API.ipynb)
  * WD [property 8024](https://www.wikidata.org/wiki/Property:P8024)
* The Swedish National Archive [SBL](https://github.com/salgo60/open-data-examples/blob/master/SBL.ipynb) 
  * WD [property 3217](https://www.wikidata.org/wiki/Property:P3217) 
* The Biographical Dictionary of Swedish Women [SKBL](https://github.com/salgo60/open-data-examples/blob/master/Svenskt%20Kvinnobiografiskt%20lexikon%20part%203.ipynb)
  * WD [property 4963](https://www.wikidata.org/wiki/Property:P4963)
* Swedish Academy - [Svenska Akademien](https://github.com/salgo60/open-data-examples/blob/master/Svenska%20Akademien.ipynb) 
  * WD [property 5325](https://www.wikidata.org/wiki/Property:P5325)

In [65]:
from datetime import datetime
start_time = datetime.now()
print("Last run: ", datetime.now())

Last run:  2021-08-09 09:30:15.211396

In [66]:
import urllib3, json
import pandas as pd 
http = urllib3.PoolManager() 

url ="https://api.nobelprize.org/2.1/laureates?offset=0&limit=1500"
dftot = pd.DataFrame()
r = http.request('GET', url)
data = json.loads(r.data)
dftot = dftot.append(pd.DataFrame(data["laureates"]),sort=False)

In [67]:
dftot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955 entries, 0 to 954
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               955 non-null    object
 1   knownName        930 non-null    object
 2   givenName        930 non-null    object
 3   familyName       928 non-null    object
 4   fullName         930 non-null    object
 5   fileName         955 non-null    object
 6   gender           930 non-null    object
 7   birth            929 non-null    object
 8   wikipedia        955 non-null    object
 9   wikidata         955 non-null    object
 10  sameAs           955 non-null    object
 11  links            955 non-null    object
 12  nobelPrizes      955 non-null    object
 13  death            639 non-null    object
 14  orgName          25 non-null     object
 15  nativeName       24 non-null     object
 16  acronym          11 non-null     object
 17  founded          24 non-null     object
 18  penName          11 non-null     object
 19  birthCountry     1 non-null      object
 20  birthCountryNow  1 non-null      object
 21  birthContinent   1 non-null      object
dtypes: object(22)
memory usage: 164.3+ KB

In [74]:
dftot["id"] = dftot["id"].astype("int")

dftot.sort_values(by=['id'], ascending=[True], inplace=True)
dftot.tail(4)

,id,knownName,givenName,familyName,fullName,fileName,gender,birth,wikipedia,wikidata,sameAs,links,nobelPrizes,death,orgName,nativeName,acronym,founded,penName,birthCountry,birthCountryNow,birthContinent
559,993,"{'en': 'Louise Glück', 'se': 'Louise Glück'}","{'en': 'Louise', 'se': 'Louise'}","{'en': 'Glück', 'se': 'Glück'}","{'en': 'Louise Glück', 'se': 'Louise Glück'}",gluck,female,"{'date': '1943-04-22', 'place': {'city': {'en'...","{'slug': 'Louise_Glück', 'english': 'https://e...","{'id': 'Q2344210', 'url': 'https://www.wikidat...","[https://www.wikidata.org/wiki/Q2344210, https...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2020', 'category': {'en': 'Lit...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
946,994,NaN,NaN,NaN,NaN,wfp,NaN,NaN,"{'slug': 'World_Food_Programme', 'english': 'h...","{'id': 'Q204344', 'url': 'https://www.wikidata...","[https://www.wikidata.org/wiki/Q204344, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2020', 'category': {'en': 'Pea...",NaN,"{'en': 'World Food Programme', 'no': 'Verdens ...",NaN,WFP,"{'date': '1961-00-00', 'place': {'locationStri...",NaN,NaN,NaN,NaN
680,995,"{'en': 'Paul R. Milgrom', 'se': 'Paul R. Milgr...","{'en': 'Paul', 'se': 'Paul'}","{'en': 'Milgrom', 'se': 'Milgrom'}","{'en': 'Paul R. Milgrom', 'se': 'Paul R. Milgr...",milgrom,male,"{'date': '1948-04-20', 'place': {'city': {'en'...","{'slug': 'Paul_Milgrom', 'english': 'https://e...","{'id': 'Q1359990', 'url': 'https://www.wikidat...","[https://www.wikidata.org/wiki/Q1359990, https...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2020', 'category': {'en': 'Eco...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
741,996,"{'en': 'Robert B. Wilson', 'se': 'Robert B. Wi...","{'en': 'Robert', 'se': 'Robert'}","{'en': 'Wilson', 'se': 'Wilson'}","{'en': 'Robert B. Wilson', 'se': 'Robert B. Wi...",wilson,male,"{'date': '1937-05-16', 'place': {'city': {'en'...","{'slug': 'Robert_B._Wilson', 'english': 'https...","{'id': 'Q377265', 'url': 'https://www.wikidata...","[https://www.wikidata.org/wiki/Q377265, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2020', 'category': {'en': 'Eco...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
#Test flatten 
#from pandas.json_normalize import json_normalize
#from pandas.io.json.normalize import nested_to_record
from pandas import json_normalize
#dftotPrize = json_normalize(data=data['laureates'], record_path='nobelPrizes', 
#                            meta=['id', 'filename','gender', 'wikidata'],errors='ignore') 
dftotPrize = json_normalize(data=data["laureates"])
dftotPrize.shape

(955, 100)

In [73]:
dftotPrize.sample(5)

,id,fileName,gender,sameAs,links,nobelPrizes,knownName.en,knownName.se,givenName.en,givenName.se,familyName.en,familyName.se,fullName.en,fullName.se,birth.date,birth.place.city.en,birth.place.city.no,birth.place.city.se,birth.place.country.en,birth.place.country.no,birth.place.country.se,birth.place.cityNow.en,birth.place.cityNow.no,birth.place.cityNow.se,birth.place.cityNow.sameAs,birth.place.countryNow.en,birth.place.countryNow.no,birth.place.countryNow.se,birth.place.countryNow.sameAs,birth.place.continent.en,birth.place.continent.no,birth.place.continent.se,birth.place.locationString.en,birth.place.locationString.no,birth.place.locationString.se,wikipedia.slug,wikipedia.english,wikidata.id,wikidata.url,death.date,death.place.city.en,death.place.city.no,death.place.city.se,death.place.country.en,death.place.country.no,death.place.country.se,death.place.country.sameAs,death.place.cityNow.en,death.place.cityNow.no,death.place.cityNow.se,death.place.cityNow.sameAs,death.place.countryNow.en,death.place.countryNow.no,death.place.countryNow.se,death.place.countryNow.sameAs,death.place.continent.en,death.place.continent.no,death.place.continent.se,death.place.locationString.en,death.place.locationString.no,death.place.locationString.se,nativeName,acronym,orgName.en,orgName.no,orgName.se,founded.date,founded.place.city.en,founded.place.city.no,founded.place.city.se,founded.place.country.en,founded.place.country.no,founded.place.country.se,founded.place.country.sameAs,founded.place.cityNow.en,founded.place.cityNow.no,founded.place.cityNow.se,founded.place.cityNow.sameAs,founded.place.countryNow.en,founded.place.countryNow.no,founded.place.countryNow.se,founded.place.countryNow.sameAs,founded.place.continent.en,founded.place.continent.no,founded.place.continent.se,founded.place.locationString.en,founded.place.locationString.no,founded.place.locationString.se,penName,birthCountry.en,birthCountry.no,birthCountry.se,birthCountryNow.en,birthCountryNow.no,birthCountryNow.se,birthContinent.en,knownName.no,givenName.no,familyName.no,fullName.no
71,33,compton,male,"[https://www.wikidata.org/wiki/Q127944, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1927', 'category': {'en': 'Phy...",Arthur H. Compton,Arthur H. Compton,Arthur H.,Arthur H.,Compton,Compton,Arthur Holly Compton,Arthur Holly Compton,1892-09-10,"Wooster, OH","Wooster, OH","Wooster, OH",USA,USA,USA,"Wooster, OH","Wooster, OH","Wooster, OH","[https://www.wikidata.org/wiki/Q989567, https:...",USA,USA,USA,[https://www.wikidata.org/wiki/Q30],North America,Nord-Amerika,Nordamerika,"Wooster, OH, USA","Wooster, OH, USA","Wooster, OH, USA",Arthur_Compton,https://en.wikipedia.org/wiki/Arthur_Compton,Q127944,https://www.wikidata.org/wiki/Q127944,1962-03-15,"Berkeley, CA","Berkeley, CA","Berkeley, CA",USA,USA,USA,https://www.wikidata.org/wiki/Q30,"Berkeley, CA","Berkeley, CA","Berkeley, CA","[https://www.wikidata.org/wiki/Q484678, https:...",USA,USA,USA,[https://www.wikidata.org/wiki/Q30],North America,Nord-Amerika,Nordamerika,"Berkeley, CA, USA","Berkeley, CA, USA","Berkeley, CA, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,327,minot,male,"[https://www.wikidata.org/wiki/Q245000, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1934', 'category': {'en': 'Phy...",George R. Minot,George R. Minot,George R.,George R.,Minot,Minot,George Richards Minot,George Richards Minot,1885-12-02,"Boston, MA","Boston, MA","Boston, MA",USA,USA,USA,"Boston, MA","Boston, MA","Boston, MA","[https://www.wikidata.org/wiki/Q100, https://w...",USA,USA,USA,[https://www.wikidata.org/wiki/Q30],North America,Nord-Amerika,Nordamerika,"Boston, MA, USA","Boston, MA, USA","Boston, MA, USA",George_Minot,https://en.wikipedia.org/wiki/George_Minot,Q245000,https://www.wikidata.org/wiki/Q245000,1950-02-25,"Brookline, MA","Brookline, MA","Brookline, MA",USA,USA,USA,https://www.wikidata.org/wiki/Q30,"Brookline, MA","Brookline, MA","Brookline, MA","[https://www.wikidata.org/wiki/Q49142, https:/...",USA,USA,USA,[https://www.wikidata.org/wiki/Q30],North America,Nord-Amerika,Nordamerika,"Brookline, MA, USA","Brookline, MA, USA","Brookline, MA, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
794,917,omura,male,"[https://www.wikidata.org/wiki/Q21061207, http...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2015', 'category': {'en': 'Phy...",Satoshi Ōmura,Satoshi Ōmura,Satoshi,Satoshi,Ōmura,Ōmura,Satoshi Ōmura,Satoshi Ōmura,1935-07-12,Yamanashi Prefecture,Yamanashi Prefecture,Yamanashi Prefecture,Japan,Japan,Japan,Yamanashi Prefecture,Yamanashi Prefecture,Yamanashi Prefecture,"[https://www.wikidata.org/wiki/Q132720, https:...",Japan,Japan,Japan,[https://www.wikidata.org/wiki/Q17],Asia,Asia,Asien,"Yamanashi Prefecture, Japan","Yamanashi Prefecture, Japan","Yamanashi Prefecture, Japan",Satoshi_Ōmura,https://en.wikipedia.org/wiki/Satoshi_Ōmura,Q21061207,https://www.wikidata.org/wiki/Q21061207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
426,690,meade,male,"[https://www.wikidata.org/wiki/Q235843, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1977', 'category': {'en': 'Eco...",James E. Meade,James E. Meade,James E.,James E.,Meade,Meade,James E. Meade,James E. Meade,1907-06-23,Swanage,Swanage,Swanage,United Kingdom,Storbritannia,Storbritannien,Swanage,Swanage,Swanage,"[https://www.wikidata.org/wiki/Q1009298, https...",United Kingdom,Storbritannia,Storbritannien,[https://www.wikidata.org/wiki/Q145],Europe,Europa,Europa,"Swanage, United Kingdom","Swanage, Storbritannia","Swanage, Storbritannien",James_Meade,https://en.wikipedia.org/wiki/James_Meade,Q235843,https://www.wikidata.org/wiki/Q235843,1995-12-22,Cambridge,Cambridge,Cambridge,United Kingdom,Storbritannia,Storbritannien,https://www.wikidata.org/wiki/Q145,Cambridge,Cambridge,Cambridge,"[https://www.wikidata.org/wiki/Q350, https://w...",United Kingdom,Storbritannia,Storbritannien,[https://www.wikidata.org/wiki/Q145],Europe,Europa,Europa,"Cambridge, United Kingdom","Cambridge, Storbritannia","Cambridge, Storbritannien",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,862,hoffmann,male,"[https://www.wikidata.org/wiki/Q105605, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2011', 'category': {'en': 'Phy...",Jules A. Hoffmann,Jules A. Hoffmann,Jules A.,Jules A.,Hoffmann,Hoffmann,Jules A. Hoffmann,Jules A. Hoffmann,1941-08-02,Echternach,Echternach,Echternach,Luxembourg,Luxembourg,Luxemburg,Echternach,Echternach,Echternach,"[https://www.wikidata.org/wiki/Q204317, https:...",Luxembourg,Luxembourg,Luxemburg,[https://www.wikidata.org/wiki/Q32],Europe,Europa,Europa,"Echternach, Luxembourg","Echternach, Luxembourg","Echternach, Luxemburg",Jules_A._Hoffmann,https://en.wikipedia.org/wiki/Jules_A._Hoffmann,Q105605,https://www.wikidata.org/wiki/Q105605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
dftotPrize["penName"].value_counts()

(pen-name of Jacques Anatole Thibault)          1
(pen-name of Rejment)                           1
(pen-name of Alexis Léger)                      1
(pen-name of Lucila Godoy y Alcayaga)           1
(pen-name of Grazia Madesani, née Deledda)      1
(pen-name of Guan Moye)                         1
(pen-name of Neftalí Ricardo Reyes Basoalto)    1
(pen-name of Giorgos Seferiadis)                1
(pen-name of René François Armand Prudhomme)    1
(pen-name of Pearl Walsh, née Sydenstricker)    1
(pen-name of Odysseus Alepoudhelis)             1
Name: penName, dtype: int64

In [77]:
dftotPrize["birth.place.countryNow.en"].value_counts()

USA                                 279
United Kingdom                       87
Germany                              82
France                               57
Sweden                               29
                                   ...
Ghana                                 1
Madagascar                            1
Zimbabwe                              1
Democratic Republic of the Congo      1
Peru                                  1
Name: birth.place.countryNow.en, Length: 82, dtype: int64

In [78]:
dftotPrize["death.place.country.sameAs"].value_counts()

https://www.wikidata.org/wiki/Q30      226
https://www.wikidata.org/wiki/Q145      80
https://www.wikidata.org/wiki/Q142      51
https://www.wikidata.org/wiki/Q183      36
https://www.wikidata.org/wiki/Q34       29
https://www.wikidata.org/wiki/Q39       28
https://www.wikidata.org/wiki/Q38       15
https://www.wikidata.org/wiki/Q17       10
https://www.wikidata.org/wiki/Q29       10
https://www.wikidata.org/wiki/Q35       10
https://www.wikidata.org/wiki/Q55       10
https://www.wikidata.org/wiki/Q20        8
https://www.wikidata.org/wiki/Q31        7
https://www.wikidata.org/wiki/Q16        6
https://www.wikidata.org/wiki/Q40        6
https://www.wikidata.org/wiki/Q159       6
https://www.wikidata.org/wiki/Q96        4
https://www.wikidata.org/wiki/Q414       4
https://www.wikidata.org/wiki/Q36        4
https://www.wikidata.org/wiki/Q801       4
https://www.wikidata.org/wiki/Q668       3
https://www.wikidata.org/wiki/Q258       3
https://www.wikidata.org/wiki/Q27        3
https://www.wikidata.org/wiki/Q33        2
https://www.wikidata.org/wiki/Q79        2
https://www.wikidata.org/wiki/Q408       2
https://www.wikidata.org/wiki/Q41        2
https://www.wikidata.org/wiki/Q1000      1
https://www.wikidata.org/wiki/Q45        1
https://www.wikidata.org/wiki/Q114       1
https://www.wikidata.org/wiki/Q881       1
https://www.wikidata.org/wiki/Q218       1
https://www.wikidata.org/wiki/Q298       1
https://www.wikidata.org/wiki/Q948       1
https://www.wikidata.org/wiki/Q766       1
https://www.wikidata.org/wiki/Q148       1
https://www.wikidata.org/wiki/Q1183      1
https://www.wikidata.org/wiki/Q28        1
https://www.wikidata.org/wiki/Q760       1
https://www.wikidata.org/wiki/Q189       1
https://www.wikidata.org/wiki/Q928       1
https://www.wikidata.org/wiki/Q334       1
https://www.wikidata.org/wiki/Q244       1
Name: death.place.country.sameAs, dtype: int64

In [5]:
dftot.sample(10)

,id,knownName,givenName,familyName,fullName,fileName,gender,birth,wikipedia,wikidata,...,nobelPrizes,death,orgName,nativeName,acronym,founded,penName,birthCountry,birthCountryNow,birthContinent
850,162,"{'en': 'Svante Arrhenius', 'se': 'Svante Arrhe...","{'en': 'Svante', 'se': 'Svante'}","{'en': 'Arrhenius', 'se': 'Arrhenius'}","{'en': 'Svante August Arrhenius', 'se': 'Svant...",arrhenius,male,"{'date': '1859-02-19', 'place': {'city': {'en'...","{'slug': 'Svante_Arrhenius', 'english': 'https...","{'id': 'Q80956', 'url': 'https://www.wikidata....",...,"[{'awardYear': '1903', 'category': {'en': 'Che...","{'date': '1927-10-02', 'place': {'city': {'en'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,475,"{'en': 'Auguste Beernaert', 'se': 'Auguste Bee...","{'en': 'Auguste', 'se': 'Auguste'}","{'en': 'Beernaert', 'se': 'Beernaert'}","{'en': 'Auguste Marie François Beernaert', 'se...",beernaert,male,"{'date': '1829-07-26', 'place': {'city': {'en'...","{'slug': 'Auguste_Marie_François_Beernaert', '...","{'id': 'Q202049', 'url': 'https://www.wikidata...",...,"[{'awardYear': '1909', 'category': {'en': 'Pea...","{'date': '1912-10-06', 'place': {'city': {'en'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,245,"{'en': 'Geoffrey Wilkinson', 'se': 'Geoffrey W...","{'en': 'Geoffrey', 'se': 'Geoffrey'}","{'en': 'Wilkinson', 'se': 'Wilkinson'}","{'en': 'Geoffrey Wilkinson', 'se': 'Geoffrey W...",wilkinson,male,"{'date': '1921-07-14', 'place': {'city': {'en'...","{'slug': 'Geoffrey_Wilkinson', 'english': 'htt...","{'id': 'Q274128', 'url': 'https://www.wikidata...",...,"[{'awardYear': '1973', 'category': {'en': 'Che...","{'date': '1996-09-26', 'place': {'city': {'en'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,564,NaN,NaN,NaN,NaN,icbl,NaN,NaN,{'slug': 'International_Campaign_to_Ban_Landmi...,"{'id': 'Q325523', 'url': 'https://www.wikidata...",...,"[{'awardYear': '1997', 'category': {'en': 'Pea...",NaN,{'en': 'International Campaign to Ban Landmine...,International Campaign to Ban Landmines (ICBL),NaN,"{'date': '1992-00-00', 'place': {'country': {'...",NaN,NaN,NaN,NaN
445,637,"{'en': 'Jean-Paul Sartre', 'se': 'Jean-Paul Sa...","{'en': 'Jean-Paul', 'se': 'Jean-Paul'}","{'en': 'Sartre', 'se': 'Sartre'}","{'en': 'Jean-Paul Sartre', 'se': 'Jean-Paul Sa...",sartre,male,"{'date': '1905-06-21', 'place': {'city': {'en'...","{'slug': 'Jean-Paul_Sartre', 'english': 'https...","{'id': 'Q9364', 'url': 'https://www.wikidata.o...",...,"[{'awardYear': '1964', 'category': {'en': 'Lit...","{'date': '1980-04-15', 'place': {'city': {'en'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,562,"{'en': 'Carlos Filipe Ximenes Belo', 'se': 'Ca...","{'en': 'Carlos Filipe Ximenes', 'se': 'Carlos ...","{'en': 'Belo', 'se': 'Belo'}","{'en': 'Carlos Filipe Ximenes Belo', 'se': 'Ca...",belo,male,"{'date': '1948-02-03', 'place': {'city': {'en'...","{'slug': 'Carlos_Filipe_Ximenes_Belo', 'englis...","{'id': 'Q234001', 'url': 'https://www.wikidata...",...,"[{'awardYear': '1996', 'category': {'en': 'Pea...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
769,806,"{'en': 'Roger D. Kornberg', 'se': 'Roger D. Ko...","{'en': 'Roger D.', 'se': 'Roger D.'}","{'en': 'Kornberg', 'se': 'Kornberg'}","{'en': 'Roger D. Kornberg', 'se': 'Roger D. Ko...",kornberg,male,"{'date': '1947-04-24', 'place': {'city': {'en'...","{'slug': 'Roger_D._Kornberg', 'english': 'http...","{'id': 'Q170676', 'url': 'https://www.wikidata...",...,"[{'awardYear': '2006', 'category': {'en': 'Che...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
655,169,"{'en': 'Otto Wallach', 'se': 'Otto Wallach'}","{'en': 'Otto', 'se': 'Otto'}","{'en': 'Wallach', 'se': 'Wallach'}","{'en': 'Otto Wallach', 'se': 'Otto Wallach'}",wallach,male,"{'date': '1847-03-27', 'place': {'city': {'en'...","{'slug': 'Otto_Wallach', 'english': 'https://e...","{'id': 'Q57127', 'url': 'https://www.wikidata....",...,"[{'awardYear': '1910', 'category': {'en': 'Che...","{'date': '1931-02-26', 'place': {'city': {'en'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766,770,"{'en': 'Roderick MacKinnon', 'se': 'Roderick M...","{'en': 'Roderick', 'se': 'Roderick'}","{'en': 'MacKinnon', 'se': 'MacKinnon'}","{'en': 'Roderick MacKinnon', 'se': 'Roderick M...",mackinnon,male,"{'date': '1956-02-19', 'place': {'city': {'en'...","{'slug': 'Roderick_MacKinnon', 'english': 'htt...","{'id': 'Q211482', 'url': 'https://www.wikidata...",...,"[{'awardYear': '2003', 'category': {'en': 'Che...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
633,402,"{'en': 'Nikolaas Tinbergen', 'se': 'Nikolaas T...","{'en': 'Nikolaas', 'se': 'Nikolaas'}","{'en': 'Tinbergen', 'se': 'Tinbergen'}","{'en': 'Nikolaas Tinbergen', 'se': 'Nikolaas T...",tinbergen,male,"{'date': '1907-04-15', 'place': {'city': {'en'...","{'slug': 'Nikolaas_Tinbergen', 'english': 'htt...","{'id': 'Q153890', 'url': 'https://www.wikidata...",...,"[{'awardYear': '1973', 'category': {'en': 'Phy...","{'date': '1988-12-21', 'place': {'city': {'en'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
listNobel = []
for index,row in dftot.iterrows():
    new_item = dict()
    new_item['id'] = row['id']
    try:
        new_item['name_en'] = row['knownName']['en']
    except:
        pass
    try:
        new_item['name_se'] = row['knownName']['se']
    except:
        pass
    new_item['link'] = row['links'][0]['href']
    try:
        new_item['awardYear'] = row['nobelPrizes'][0]['awardYear']
        new_item['category'] = row['nobelPrizes'][0]['category']['en']
    except:
        pass
    try:
        new_item['sameas'] = row['sameas']
    except:
        pass
    try:
        new_item['gender'] = row['gender']
    except:
        pass
    try:
        new_item['wikidata'] = row['wikidata']['id']
    except:
        pass
    listNobel.append(new_item)
NobelTot = pd.DataFrame(listNobel,
                  columns=['id','wikidata','name_en','name_se','link','gender','awardYear','category','sameas'])

NobelTot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955 entries, 0 to 954
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         955 non-null    int64
 1   wikidata   955 non-null    object
 2   name_en    930 non-null    object
 3   name_se    930 non-null    object
 4   link       955 non-null    object
 5   gender     930 non-null    object
 6   awardYear  955 non-null    object
 7   category   955 non-null    object
 8   sameas     0 non-null      float64
dtypes: float64(1), int64(1), object(7)
memory usage: 67.3+ KB

## Check Wikidata matches

In [22]:
# pip install sparqlwrapper
# https://rdflib.github.io/sparqlwrapper/

import sys
from SPARQLWrapper import SPARQLWrapper, JSON

endpoint_url = "https://query.wikidata.org/sparql"

query = """SELECT ?item ?itemLabel ?NobelAPI WHERE {
  ?item wdt:P8024 ?NobelAPI.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
} order by xsd:integer(?NobelAPI)"""


def get_sparql_dataframe(endpoint_url, query):
    """
    Helper function to convert SPARQL results into a Pandas data frame.
    """
    user_agent = "salgo60/%s.%s" % (sys.version_info[0], sys.version_info[1])
 
    sparql = SPARQLWrapper(endpoint_url, agent=user_agent)
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    result = sparql.query()

    processed_results = json.load(result.response)
    cols = processed_results['head']['vars']
    out = []
    for row in processed_results['results']['bindings']:
        item = []
        for c in cols:
            item.append(row.get(c, {}).get('value'))
        out.append(item)

    return pd.DataFrame(out, columns=cols)

WDNobel = get_sparql_dataframe(endpoint_url, query)

In [23]:
WDNobel["NobelAPI"] = WDNobel["NobelAPI"].astype("int")
WDNobel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955 entries, 0 to 954
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   item       955 non-null    object
 1   itemLabel  955 non-null    object
 2   NobelAPI   955 non-null    int64
dtypes: int64(1), object(2)
memory usage: 22.5+ KB

### Compare WD <-> Nobel

In [9]:
dfmerge = pd.merge(WDNobel, NobelTot,how='outer', left_on="NobelAPI",right_on="id",indicator=True)
dfmerge['_merge'] = dfmerge['_merge'].str.replace('left_only','WD_only').str.replace('right_only','Nobel_only')
dfmerge.rename(columns={"_merge": "WD_Nobel"},inplace = True)    
#dfmerge[-10:]

In [38]:
dfmerge[dfmerge["WD_Nobel"]!="both"]

Empty DataFrame
Columns: [item, itemLabel, NobelAPI, id, name_en, name_se, link, gender, awardYear, category, sameas, WD_Nobel, linkjson, linkhtml, wd]
Index: []

In [32]:
WDNobel['wikidata'] = WDNobel['item'].str.replace('http://www.wikidata.org/entity/','')

<ipython-input-32-0e6ca1d6257f>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  WDNobel['wikidata'] = WDNobel['item'].str.replace('http://www.wikidata.org/entity/','')

In [33]:
WDNobel.head()

,item,itemLabel,NobelAPI,Q,wikidata
0,http://www.wikidata.org/entity/Q35149,Wilhelm Röntgen,1,Q35149,Q35149
1,http://www.wikidata.org/entity/Q41688,Hendrik Lorentz,2,Q41688,Q41688
2,http://www.wikidata.org/entity/Q79000,Pieter Zeeman,3,Q79000,Q79000
3,http://www.wikidata.org/entity/Q41269,Henri Becquerel,4,Q41269,Q41269
4,http://www.wikidata.org/entity/Q37463,Pierre Curie,5,Q37463,Q37463

In [31]:
NobelTot.head()

,id,wikidata,name_en,name_se,link,gender,awardYear,category,sameas
0,1,Q35149,Wilhelm Conrad Röntgen,Wilhelm Conrad Röntgen,https://api.nobelprize.org/2/laureate/1,male,1901,Physics,NaN
1,2,Q41688,Hendrik A. Lorentz,Hendrik A. Lorentz,https://api.nobelprize.org/2/laureate/2,male,1902,Physics,NaN
2,3,Q79000,Pieter Zeeman,Pieter Zeeman,https://api.nobelprize.org/2/laureate/3,male,1902,Physics,NaN
3,4,Q41269,Henri Becquerel,Henri Becquerel,https://api.nobelprize.org/2/laureate/4,male,1903,Physics,NaN
4,5,Q37463,Pierre Curie,Pierre Curie,https://api.nobelprize.org/2/laureate/5,male,1903,Physics,NaN

In [36]:
#Merge on the Wikidata Qnumber at NobelTot  
dfmergeWD = pd.merge(WDNobel, NobelTot,how='outer', on="wikidata",indicator=True)
dfmergeWD['_merge'] = dfmergeWD['_merge'].str.replace('left_only','WD_only').str.replace('right_only','Nobel_only')
dfmergeWD.rename(columns={"_merge": "WD_Nobel"},inplace = True)    
dfmergeWD["WD_Nobel"].value_counts()

both          954
Nobel_only      2
WD_only         1
Name: WD_Nobel, dtype: int64

In [37]:
dfmergeWD[dfmergeWD["WD_Nobel"]!="both"]

,item,itemLabel,NobelAPI,Q,wikidata,id,name_en,name_se,link,gender,awardYear,category,sameas,WD_Nobel
806,http://www.wikidata.org/entity/Q42037,Jean-Marie Gustave Le Clézio,832.0,Q42037,Q42037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WD_only
955,NaN,NaN,NaN,NaN,Q1069175,523.0,NaN,NaN,https://api.nobelprize.org/2/laureate/523,NaN,1963,Peace,NaN,Nobel_only
956,NaN,NaN,NaN,NaN,Q7884119,832.0,Jean-Marie Gustave Le Clézio,Jean-Marie Gustave Le Clézio,https://api.nobelprize.org/2/laureate/832,male,2008,Literature,NaN,Nobel_only

#### Check that Wikidata and api.nobelprize.org is in synch

In [10]:
dfmerge["WD_Nobel"].value_counts()

both    955
Name: WD_Nobel, dtype: int64

In [11]:
Nobelonly = dfmerge[dfmerge["WD_Nobel"]=="Nobel_only"].copy() 

from IPython.display import HTML
Nobelonly["Nobel"] = "<a href='https://api.nobelprize.org/v1/laureate.json?id=" + Nobelonly["id"] + "'>link</a>"
Nobelonly["Nobelhtml"] = "<a href='https://www.nobelprize.org/laureate/" + Nobelonly["id"] + "'>html</a>"
pd.set_option("display.max.columns", None) 
HTML(Nobelonly.to_html(escape=False))

In [39]:
dfmerge.to_csv("Nobel_dfmerge.csv")

In [12]:
WDonly = dfmerge[dfmerge["WD_Nobel"]=="WD_only"].copy() 
WDonly

Empty DataFrame
Columns: [item, itemLabel, NobelAPI, id, name_en, name_se, link, gender, awardYear, category, sameas, WD_Nobel]
Index: []

In [13]:
print("End run: ", datetime.now())

End run:  2021-07-31 15:11:16.056950

In [14]:
print('Time elapsed (hh:mm:ss.ms) {}'.format(datetime.now() - start_time))

Time elapsed (hh:mm:ss.ms) 0:00:12.450726

#### Lesson learned
Its a delay when the html page is linked after the announcement --> we do this list below to check when its ready and we can add it to Wikidata and the WIkipedia article

In [15]:
# see task xxx we can create links JSOn and HTML using the ID
dfmerge["linkjson"] = "<a href='https://api.nobelprize.org/v1/laureate.json?id=" + dfmerge["id"].astype(str) + "'>json</a>"
dfmerge["linkhtml"] = "<a href='https://www.nobelprize.org/laureate/" + dfmerge["id"].astype(str) + "'>html</a>"
dfmerge["wd"] = "<a href='" + dfmerge["item"].astype(str) + "'>Wikidata</a>"

pd.set_option("display.max.columns", None) 
HTML(dfmerge[{'wd','name_en','awardYear','category','linkjson','linkhtml'}].tail(15).to_html(escape=False))

Status 20201009 :
* Ok all has html pages

Templates supporting Wikidata Property 8024 = Wikidata [Q91652187](https://www.wikidata.org/wiki/Q91652187)
* ar:Wikipedia [قالب:جائزة_نوبل](https://ar.wikipedia.org/wiki/%D9%82%D8%A7%D9%84%D8%A8:%D8%AC%D8%A7%D8%A6%D8%B2%D8%A9_%D9%86%D9%88%D8%A8%D9%84)
* ca:wikipedia [Plantilla:Nobelprize](https://ca.wikipedia.org/wiki/Plantilla:Nobelprize)
* en:Wikipedia [Template:Nobelprize](https://en.wikipedia.org/wiki/Template:Nobelprize)
* ka:Wikipedia [თარგი:Nobelprize](https://ka.wikipedia.org/wiki/%E1%83%97%E1%83%90%E1%83%A0%E1%83%92%E1%83%98:Nobelprize)
* nn:Wikipedia [Mal:Nobelprize](https://nn.wikipedia.org/wiki/Mal:Nobelprize)
* pt:Wikipedia [Predefinição:Prémio Nobel](https://pt.wikipedia.org/wiki/Predefini%C3%A7%C3%A3o:Pr%C3%A9mio_Nobel)
* sv:Wikipedia [Mall:Nobelprize](https://sv.wikipedia.org/wiki/Mall:Nobelprize)
* sr:WIkipedia [Шаблон:Nobelprize](https://sr.wikipedia.org/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:Nobelprize)

* Articles using [template](https://www.wikidata.org/wiki/Q91652187) and view statistics this year and during the [Nobel week](https://www.nobelprize.org/press/#/publication/5f1719e411aab40004a17f36/552bd85dccc8e20c00e7f979?&sh=false)  5-12 October 2020 on those articles see also [video](https://youtu.be/Iu1JtefueM8)
  * ar:Wikipedia [using](https://petscan.wmflabs.org/?psid=17573153) / not using
    * [statistics](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&range=this-year&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://ar.wikipedia.org/wiki/%25D8%25AA%25D8%25B5%25D9%2586%25D9%258A%25D9%2581:%25D9%2582%25D8%25A7%25D9%2584%25D8%25A8_%25D8%25AC%25D8%25A7%25D8%25A6%25D8%25B2%25D8%25A9_%25D9%2586%25D9%2588%25D8%25A8%25D9%2584_%25D9%258A%25D8%25B3%25D8%25AA%25D8%25B9%25D9%2585%25D9%2584_%25D8%25AE%25D8%25A7%25D8%25B5%25D8%25A9_%25D9%2588%25D9%258A%25D9%2583%25D9%258A_%25D8%25A8%25D9%258A%25D8%25A7%25D9%2586%25D8%25A7%25D8%25AA_P8024) / [Nobel week](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-12&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://ar.wikipedia.org/wiki/%25D8%25AA%25D8%25B5%25D9%2586%25D9%258A%25D9%2581:%25D9%2582%25D8%25A7%25D9%2584%25D8%25A8_%25D8%25AC%25D8%25A7%25D8%25A6%25D8%25B2%25D8%25A9_%25D9%2586%25D9%2588%25D8%25A8%25D9%2584_%25D9%258A%25D8%25B3%25D8%25AA%25D8%25B9%25D9%2585%25D9%2584_%25D8%25AE%25D8%25A7%25D8%25B5%25D8%25A9_%25D9%2588%25D9%258A%25D9%2583%25D9%258A_%25D8%25A8%25D9%258A%25D8%25A7%25D9%2586%25D8%25A7%25D8%25AA_P8024)
  * ca:Wikipedia miss track category [Q91672712](https://www.wikidata.org/wiki/Q91672712#sitelinks-wikipedia)
  * en:Wikipedia [using](https://petscan.wmflabs.org/?psid=17573140) / [not using](https://petscan.wmflabs.org/?psid=17579263) 
    * [statistics](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&range=this-year&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://en.wikipedia.org/wiki/Category:Nobelprize_template_using_Wikidata_property_P8024) / [Nobel week](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-12&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://en.wikipedia.org/wiki/Category:Nobelprize_template_using_Wikidata_property_P8024) as a [chart](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-10&subjectpage=0&subcategories=0&sort=views&direction=1&view=chart&target=https://en.wikipedia.org/wiki/Category:Nobelprize%20template%20using%20Wikidata%20property%20P8024)
  * ka:Wikipedia miss track category [Q91672712](https://www.wikidata.org/wiki/Q91672712#sitelinks-wikipedia)
  * nn:Wikipedia [using](https://petscan.wmflabs.org/?psid=17573155) / not using 
     * [statistics](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&range=this-year&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://nn.wikipedia.org/wiki/Kategori:Sider_som_nyttar_Mal:Nobelprize) / [Nobel week](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-12&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://nn.wikipedia.org/wiki/Kategori:Sider_som_nyttar_Mal:Nobelprize)
  * pt:Wikipedia [using](https://petscan.wmflabs.org/?psid=17573158) / [not using](https://petscan.wmflabs.org/?psid=17579612) 
     * [statistics](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&range=this-year&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://pt.wikipedia.org/wiki/Categoria:Predefini%25C3%25A7%25C3%25A3o_sobre_pr%25C3%25A9mios_Nobel_que_usam_a_propriedade_do_Wikidata_P8024) / [Nobel week](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-12&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://pt.wikipedia.org/wiki/Categoria:Predefini%25C3%25A7%25C3%25A3o_sobre_pr%25C3%25A9mios_Nobel_que_usam_a_propriedade_do_Wikidata_P8024)
  * sv:Wikipedia [using](https://petscan.wmflabs.org/?psid=17573129) / not using 
    * [statistics](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&range=this-year&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://sv.wikipedia.org/wiki/Kategori:Sidor_som_anv%25C3%25A4nder_Mall:Nobelprize) / [Nobel week](https://pageviews.toolforge.org/massviews/?platform=all-access&agent=user&source=category&start=2020-10-05&end=2020-10-12&subjectpage=0&subcategories=0&sort=views&direction=1&view=list&target=https://sv.wikipedia.org/wiki/Kategori:Sidor_som_anv%25C3%25A4nder_Mall:Nobelprize)
  * sr:Wikipedia miss track category [Q91672712](https://www.wikidata.org/wiki/Q91672712#sitelinks-wikipedia)
  
Task [T251055](https://phabricator.wikimedia.org/T251055)

# Next Nobelprize announcement
see https://www.nobelprize.org/